In [1]:
# Update sklearn to prevent version mismatches
!pip install sklearn --upgrade

Collecting sklearn
  Downloading sklearn-0.0.tar.gz (1.1 kB)
Requirement already satisfied, skipping upgrade: scikit-learn in c:\users\lucie\anaconda3\lib\site-packages (from sklearn) (0.23.1)
Requirement already satisfied, skipping upgrade: numpy>=1.13.3 in c:\users\lucie\anaconda3\lib\site-packages (from scikit-learn->sklearn) (1.19.5)
Requirement already satisfied, skipping upgrade: joblib>=0.11 in c:\users\lucie\anaconda3\lib\site-packages (from scikit-learn->sklearn) (0.16.0)
Requirement already satisfied, skipping upgrade: threadpoolctl>=2.0.0 in c:\users\lucie\anaconda3\lib\site-packages (from scikit-learn->sklearn) (2.1.0)
Requirement already satisfied, skipping upgrade: scipy>=0.19.1 in c:\users\lucie\anaconda3\lib\site-packages (from scikit-learn->sklearn) (1.5.0)
Building wheels for collected packages: sklearn
  Building wheel for sklearn (setup.py): started
  Building wheel for sklearn (setup.py): finished with status 'done'
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1316 sha256=23e76f14f4194bc1235eecd8c56790e5c05d973e117da10fc233f292a2284030
  Stored in directory: c:\users\lucie\appdata\local\pip\cache\wheels\22\0b\40\fd3f795caaa1fb4c6cb738bc1f56100be1e57da95849bfc897
Successfully built sklearn
Installing collected packages: sklearn
Successfully installed sklearn-0.0

In [2]:
# install joblib. This will be used to save your model. 
# Restart your kernel after installing 
!pip install joblib

Requirement already satisfied: joblib in c:\users\lucie\anaconda3\lib\site-packages (0.16.0)

In [3]:
import pandas as pd

# Read the CSV and Perform Basic Data Cleaning

In [4]:
df = pd.read_csv("exoplanet_data.csv")
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df.head()

,koi_disposition,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,koi_time0bk_err1,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,CONFIRMED,0,0,0,0,54.418383,2.479000e-04,-2.479000e-04,162.513840,0.003520,...,-81,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,FALSE POSITIVE,0,1,0,0,19.899140,1.490000e-05,-1.490000e-05,175.850252,0.000581,...,-176,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
2,FALSE POSITIVE,0,1,0,0,1.736952,2.630000e-07,-2.630000e-07,170.307565,0.000115,...,-174,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
3,CONFIRMED,0,0,0,0,2.525592,3.760000e-06,-3.760000e-06,171.595550,0.001130,...,-211,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509
4,CONFIRMED,0,0,0,0,4.134435,1.050000e-05,-1.050000e-05,172.979370,0.001900,...,-232,4.486,0.054,-0.229,0.972,0.315,-0.105,296.28613,48.224670,15.714

# Select your features (columns)

In [6]:
# show columns
df.columns

Index(['koi_disposition', 'koi_fpflag_nt', 'koi_fpflag_ss', 'koi_fpflag_co',
       'koi_fpflag_ec', 'koi_period', 'koi_period_err1', 'koi_period_err2',
       'koi_time0bk', 'koi_time0bk_err1', 'koi_time0bk_err2', 'koi_impact',
       'koi_impact_err1', 'koi_impact_err2', 'koi_duration',
       'koi_duration_err1', 'koi_duration_err2', 'koi_depth', 'koi_depth_err1',
       'koi_depth_err2', 'koi_prad', 'koi_prad_err1', 'koi_prad_err2',
       'koi_teq', 'koi_insol', 'koi_insol_err1', 'koi_insol_err2',
       'koi_model_snr', 'koi_tce_plnt_num', 'koi_steff', 'koi_steff_err1',
       'koi_steff_err2', 'koi_slogg', 'koi_slogg_err1', 'koi_slogg_err2',
       'koi_srad', 'koi_srad_err1', 'koi_srad_err2', 'ra', 'dec',
       'koi_kepmag'],
      dtype='object')

In [8]:
# Set features. This will also be used as your x values.
selected_features = df[["koi_impact","koi_time0bk","koi_period","koi_slogg","koi_depth","koi_prad","koi_insol","koi_model_snr","koi_tce_plnt_num","koi_steff"]]

selected_features

,koi_impact,koi_time0bk,koi_period,koi_slogg,koi_depth,koi_prad,koi_insol,koi_model_snr,koi_tce_plnt_num,koi_steff
0,0.586,162.513840,54.418383,4.467,874.8,2.83,9.11,25.8,2,5455
1,0.969,175.850252,19.899140,4.544,10829.0,14.60,39.30,76.3,1,5853
2,1.276,170.307565,1.736952,4.564,8079.2,33.46,891.96,505.6,1,5805
3,0.701,171.595550,2.525592,4.438,603.3,2.75,926.16,40.9,1,6031
4,0.762,172.979370,4.134435,4.486,686.0,2.77,427.65,40.2,2,6046
...,...,...,...,...,...,...,...,...,...,...
6986,0.765,132.016100,8.589871,4.296,87.7,1.11,176.40,8.4,1,5638
6987,1.252,131.705093,0.527699,4.529,1579.2,29.35,4500.53,453.3,1,5638
6988,0.043,133.001270,1.739849,4.444,48.5,0.72,1585.81,10.6,1,6119
6989,0.147,132.181750,0.681402,4.447,103.6,1.07,5713.41,12.3,1,6173
6990,0.134,135.993300,4.856035,4.385,76.7,1.05,607.42,8.2,1,6469

# Create a Train Test Split

Use `koi_disposition` for the y values

In [9]:
y = df["koi_disposition"]

In [10]:
y

0            CONFIRMED
1       FALSE POSITIVE
2       FALSE POSITIVE
3            CONFIRMED
4            CONFIRMED
             ...
6986    FALSE POSITIVE
6987    FALSE POSITIVE
6988         CANDIDATE
6989    FALSE POSITIVE
6990    FALSE POSITIVE
Name: koi_disposition, Length: 6991, dtype: object

In [13]:

# split data into training and testing
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(selected_features, y, random_state=42)

In [14]:
X_train.head()

,koi_impact,koi_time0bk,koi_period,koi_slogg,koi_depth,koi_prad,koi_insol,koi_model_snr,koi_tce_plnt_num,koi_steff
6122,0.150,133.077240,6.768901,4.327,123.1,1.24,253.30,10.8,1,5737
6370,0.291,132.020050,0.733726,4.578,114.6,0.86,2891.64,13.8,1,5855
2879,0.970,134.460380,7.652707,4.481,641.1,3.21,226.81,254.3,1,6328
107,0.300,174.662240,7.953547,4.536,875.4,2.25,55.37,38.4,1,4768
29,0.831,172.258529,4.959319,4.359,9802.0,12.21,349.40,696.5,1,5712

# Pre-processing

Scale the data using the MinMaxScaler and perform some feature selection

In [ ]:
# Scale your data
X2 = df.drop(columns=["koi_disposition"])
X2_train, X2_test, y_train, y_test = train_test_split(X2, y, random_state=23)

In [ ]:
X2_train.head()

# Train the Model

In [15]:
print(f"Training Data Score: {model2.score(X_train_scaled, y_train)}")
print(f"Testing Data Score: {model2.score(X_test_scaled, y_test)}")

NameError: name 'model2' is not defined

# Hyperparameter Tuning

Use `GridSearchCV` to tune the model's parameters

In [ ]:
# Create the GridSearchCV model

In [ ]:
# Train the model with GridSearch

In [ ]:
print(grid2.best_params_)
print(grid2.best_score_)

# Save the Model

In [ ]:
# save your model by updating "your_name" with your name
# and "your_model" with your model variable
# be sure to turn this in to BCS
# if joblib fails to import, try running the command to install in terminal/git-bash
import joblib
filename = 'your_name.sav'
joblib.dump(your_model, filename)